### ISSUE TITLE
theme for markdown editor

### ISSUE THREAD

**Issue by ghtea** [ghtea/blog#15]
## Description
add theme for markdown editor

**Todo**
- [x] add general css properties
- [x] add dark mode colors
- [x] add render editor and preview in draft page
