### ISSUE TITLE
마크다운 에디터, 뷰어 테마 개선

### ISSUE THREAD

**Issue by ghtea** [ghtea/blog#17]
## Description
마크다운 에디터, 뷰어 테마 개선

**Todo**
- [x] add list tag styles
- [x] add link tag styles
- [x] add better colors
